export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-black via-zinc-900 to-red-800 py-12 px-6">
      <div className="max-w-4xl mx-auto bg-[#111111] text-white border border-red-900 rounded-2xl shadow-lg p-8">
        <h1 className="text-4xl font-bold mb-6">
          Terms & Conditions
        </h1>

        <p className="mb-4">
          By using DRAKSYON, you agree to these Terms and Conditions.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">
          Use of Services
        </h2>

        <p className="mb-4">
          All tools and services provided on DRAKSYON are offered for
          informational and general use purposes only.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">
          No Warranty
        </h2>

        <p className="mb-4">
          We do not guarantee the accuracy, completeness, or reliability
          of any calculations or results generated by our tools.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">
          Limitation of Liability
        </h2>

        <p className="mb-4">
          DRAKSYON shall not be held responsible for any loss or damages
          resulting from the use of our website or tools.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">
          Contact
        </h2>

        <p>
          For any questions regarding these Terms & Conditions,
          please contact:
          <br />
          draksyon.support@gmail.com
        </p>
      </div>
    </main>
  );
}