export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-zinc-950 text-white px-6 py-12">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl md:text-6xl font-extrabold text-center mb-6">
          Disclaimer{" "}
          <span className="text-red-500">
            Notice
          </span>
        </h1>

        <div className="space-y-6 text-zinc-300 leading-relaxed">

          <p>
            The information and tools provided on Darksyon are for general
            informational and educational purposes only.
          </p>

          <p>
            While we strive to keep all information accurate and up to date,
            Darksyon makes no warranties regarding the completeness,
            reliability, or accuracy of any information generated by our tools.
          </p>

          <p>
            AI-generated content may contain inaccuracies and should always be
            reviewed before being used for professional, legal, financial, or
            business purposes.
          </p>

          <p>
            Users are responsible for how they use the information and outputs
            generated through this website.
          </p>

          <p>
            Darksyon shall not be held liable for any losses, damages, or
            consequences resulting from the use of this website or its tools.
          </p>

          <p>
            By using this website, you agree to this disclaimer and its terms.
          </p>

        </div>
      </div>
    </main>
  );
}